// Publicaciones de ejemplo para desarrollo (npm run fixture). Charlas sobre notas de las rutas de
// lectura de 421 (421.news/es/rutas). Cada publicación: tablón, asunto, hace cuántas horas arrancó
// y los mensajes en orden. El primero es el inicial. Un mensaje puede ser:
//   'texto'                   lo escribe alguien que todavía no habló en la publicación
//   { op: 'texto' }           lo escribe quien abrió la publicación
//   { de: 2, t: 'texto' }     lo escribe el mismo que el mensaje 2 (el inicial es el 0)
//   { sage: true, t: '...' }  responde sin subir la publicación
// Dentro del texto, >>#N cita al mensaje N de la misma publicación.

export const HILOS = [
  {
    tablon: 'cultura',
    asunto: 'The Thing (1982) en el Canon',
    horas: 70,
    mensajes: [
      'lei la entrega del canon sobre the thing y la volvi a ver el finde, sigue dando miedo la escena del test de sangre no hay caso',
      'la del desfibrilador es peor',
      { de: 1, t: 'la del pecho q se abre?? jajaja no la puedo ver hasta hoy' },
      'lo mejor de la nota es lo de la paranoia, q no sabes quien es quien',
      { op: '>>#3 si eso lo explica bien, el bicho es lo de menos' },
      'el final [spoiler]MacReady y Childs mirandose con la botella[/spoiler] es perfecto',
      'nunca la vi, la anoto',
      { de: 1, t: '>>#6 de noche y solo, es la unica forma' },
      'la musica de morricone es medio un zumbido y funciona igual',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'alguien siguio la guia de lectura de ciencia ficcion?',
    horas: 52,
    mensajes: [
      'voy por el cuarto libro de la guia y ya no se cual sigue. arranque por los q tenia en casa',
      'cuales leiste',
      { op: 'Solaris, Ubik, La mano izquierda de la oscuridad y uno de ballard' },
      'ubik jajaja que viaje',
      'segui con picnic extraterrestre q es cortito',
      { de: 4, t: 'y si te gusto ballard, crash. hay una nota en 421 sobre eso tmb' },
      'yo me trabe con dune lo deje 2 veces',
      { de: 6, t: 'igual, las primeras 100 paginas son un tramite' },
      { op: '>>#4 anotado gracias!' },
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'hice el pan de la nota de 421',
    horas: 45,
    mensajes: [
      'primer intento salio chato pero rico, el segundo bien y el tercero se me quemo abajo. segui la receta de 421 al pie de la letra eh',
      'jajaja el tercero es el que cuenta',
      'el horno de casa calienta mas abajo, pone una fuente con agua en la parrila de abajo',
      { op: '>>#2 no sabia, pruebo' },
      'cuanto lo dejas levar?',
      { op: 'como 2 horas, en invierno mas' },
      'yo lo hago a la noche y lo dejo en la heladera, a la mañana al horno',
      'lo que dice la nota de q es terapeutico es verdad eh',
      { de: 1, t: 'hasta q se quema' },
      { sage: true, t: 'foto no se puede subir asi que confiamos' },
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'Parque Rivadavia',
    horas: 40,
    mensajes: [
      'lei la historia del parque rivadavia en 421. iba de chico con mi viejo a cambiar figuritas y revistas, no sabia q venia de tan lejos',
      'yo compre ahi mis primeros discos truchos jaja',
      'sigue la feria de libros los domingos?',
      { op: '>>#2 si fui hace un mes' },
      'ahi consegui casi todas las Pendulo',
      'cambiaba cartas de magic ahi en los 90',
      { de: 5, t: 'y te cagaban siempre' },
      'jajaja',
      { op: 'la nota tiene fotos viejas buenisimas' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'Argentinosaurus 35 metros',
    horas: 38,
    mensajes: [
      '35 metros y 75 toneladas, no me entra en la cabeza. es un edificio de 10 pisos acostado',
      'hay una replica en el museo carmen funes en plaza huincul',
      { op: '>>#1 lo tengo pendiente hace años' },
      'tmb esta el catalogo de dinosaurios argentinos, la primera entrega, buenisimo',
      'de chico queria ser paleontologo y termine en sistemas jaja',
      { de: 4, t: 'como todos' },
      'lo q no entiendo es como caminaba con ese peso',
      { op: '>>#6 lo explica al final, la parte de la fisica' },
    ],
  },
  {
    tablon: 'juegos',
    asunto: 'Dark Souls y la tragedia griega',
    horas: 33,
    mensajes: [
      'no conocia a lesky y ahora tengo ganas de volver a jugarlo. muy buena la nota',
      'volve, siempre hay que volver',
      'yo lo deje en blighttown no me da la paciencia',
      { de: 2, t: 'y el framerate tampoco ayuda' },
      'lo del protagonista que va hacia su propia caida esta bien visto',
      { op: '>>#2 blighttown es un filtro, pasas eso y listo' },
      { de: 2, t: 'dijeron lo mismo de sen\'s fortress jaja' },
      'praise the sun',
      { sage: true, t: 'la de who\'s lila tmb esta buena, otra onda' },
    ],
  },
  {
    tablon: 'juegos',
    asunto: 'alguien hizo su propio juego de mesa?',
    horas: 30,
    mensajes: [
      'con la guia de 421 para hacer y testear tu juego de mesa. estoy con uno de cartas, voy por la version 3 del prototipo todo en cartulina',
      'de que se trata?',
      { op: 'de repartir pizzas en una ciudad, cada jugador tiene una moto y una ruta' },
      'jajajaja me encanta',
      'lo de testear con gente q no te conoce es lo mas dificil',
      { op: '>>#4 si mis amigos me dicen q esta todo bien siempre' },
      'probá llevarlo a un club de juegos',
      'si queres testers avisa',
      { op: '>>#7 dale cuando tenga la v4' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'Android sin google en un moto g7',
    horas: 27,
    mensajes: [
      'segui la nota para sacarle google al celu. tenia un g7 tirado en un cajon, anduvo pero tarde una tarde entera',
      'que rom usaste',
      { op: 'lineageos sin gapps' },
      'y el home banking?',
      { op: '>>#3 ese es el problema jaja uno anda y el otro no' },
      'yo lo uso de segundo telefono para lo basico',
      'lo del mapa sin google como lo resolviste',
      { op: '>>#6 osmand, bajas los mapas y anda sin datos' },
      { de: 3, t: 'mañana pruebo con un g6 q tengo' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'selfhosting, que tienen corriendo en casa',
    horas: 24,
    mensajes: [
      'despues de leer lo de la nube hogareña arme algo con una compu vieja, por ahora solo fotos y un par de cosas. ustedes q tienen?',
      'jellyfin y un nextcloud en una raspberry',
      'yo solo un server de minecraft para mis sobrinos jaja',
      { op: '>>#2 eso tmb cuenta' },
      'el problema es cuando se corta la luz',
      { de: 1, t: 'ups y a rezar' },
      'backups??',
      { op: '>>#6 ...' },
      'jajaja',
      { de: 6, t: 'hace backups' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'modelos locales con la guia de 421',
    horas: 20,
    mensajes: [
      'lo probe en una notebook con 16 de ram y anda, lento pero anda. segui la guia paso a paso',
      'que modelo?',
      { op: 'uno chico de 7B, lo q entraba' },
      'con placa de video cambia todo',
      'yo lo uso para resumir pdfs del laburo, no los quiero subir a ningun lado',
      { op: '>>#4 para eso lo queria yo tmb' },
      'la notebook se calienta como una plancha no?',
      { op: '>>#6 jaja un poco' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'fanzines',
    horas: 18,
    mensajes: [
      'armamos uno con mi hermana siguiendo la guia. 8 paginas fotocopia blanco y negro, sacamos 30',
      'de que es',
      { op: 'recetas de la abuela con dibujos' },
      'que lindo eso',
      'tengo una caja con fanzines de los 2000 no los tiro mas',
      'lo de doblar una sola hoja y q te queden 8 paginas me volo la cabeza',
      { op: '>>#5 a mi tmb jaja' },
      { de: 4, t: 'donde se consiguen ahora? ferias?' },
      'en ferias y en alguna libreria chica',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'Borges y los backrooms',
    horas: 15,
    mensajes: [
      'yo pensaba q los backrooms eran un creepypasta y ya, ahora quiero releer la biblioteca de babel',
      'la peli la viste?',
      { op: 'todavia no' },
      'esta bien, dura un poco de mas',
      'el pasillo amarillo con el zumbido de los tubos es lo mas perturbador q hay',
      '>la geometria caotica\nme acorde de la casa de asterion tmb',
      { op: '>>#5 si la nombra' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'star wars y derecho constitucional',
    horas: 13,
    mensajes: [
      'nunca pense q iba a leer una nota sobre las precuelas y el estado de excepcion y que me iba a gustar',
      'las precuelas eran cine politico y de chicos no nos dimos cuenta',
      { op: '>>#1 jajaja yo de chico solo queria ver a darth maul' },
      'toda la parte del senado q era aburridisima era lo importante',
      'no me gusta la arena',
      { de: 4, t: 'es aspera' },
      'jajajaja',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'Kayfabe',
    horas: 11,
    mensajes: [
      'no sabia q "shoot" es cuando algo pasa de verdad. ahora lo veo en todos lados',
      'de chico miraba titanes en el ring y me creia todo',
      { op: '>>#1 jaja la momia' },
      'martin karadagian',
      'la nota explica bien lo de "trabajar" al publico',
      { de: 1, t: 'a mi me trabajaron durante años' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'drones fpv vale la pena arrancar?',
    horas: 9,
    mensajes: [
      'tengo ganas de arrancar pero me da miedo romper todo el primer dia. lei la intro y quede manija',
      'arranca con simulador si o si',
      { op: 'cual?' },
      { de: 1, t: 'cualquiera con un control barato, unas 20 horas y despues el dron' },
      'yo rompi dos helices el primer dia y era un tiny whoop',
      { op: '>>#4 jajaja' },
      'y averigua bien donde se puede volar',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'Homestuck',
    horas: 7,
    mensajes: [
      'lo lei entero en 2012 y no me acuerdo de la mitad, con la nota me acorde de un monton de cosas',
      'nunca lo termine es eterno',
      'yo ni sabia q era hasta la nota',
      { op: '>>#2 no empieces jaja' },
      'q los fans lo sigan sosteniendo hasta hoy esta bueno',
      { de: 1, t: 'el acto 6 me mato' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'rutas de lectura, por cual arrancaron?',
    horas: 5,
    mensajes: [
      'vi que 421 armo rutas de lectura, 8 recorridos de 8 notas cada uno. por cual arrancaron?',
      'hacelo vos mismo. la del pan jaja',
      'el canon del entretenimiento, ya habia leido varias sueltas',
      'internet no murio',
      { op: '>>#1 yo tmb, ya hice el pan' },
      { de: 2, t: 'me faltan robocop y gojira' },
      'argentina como laboratorio x los dinosaurios',
      'esta bueno q tengan un orden asi no saltas de nota en nota al azar',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'Gojira 1954',
    horas: 4,
    mensajes: [
      'vi la original despues de leer la del canon. es mucho mas triste de lo q pensaba, nada que ver con las yanquis',
      'la nota explica bien lo del trauma nuclear, se entiende todo distinto',
      'el tipo adentro del traje sufria en serio',
      { op: '>>#2 jaja pobre' },
      'la escena del hospital es durisima',
      { sage: true, t: 'shin godzilla tmb es buena' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'soulseek sigue vivo',
    horas: 3,
    mensajes: [
      'por la nota "ya pagas internet, no pagues por lo demas" volvi a instalar soulseek despues de como 15 años. esta igual jaja. encontre discos q no estan en ningun lado',
      'la interfaz de 2004 jajaja',
      'lo mejor es entrar a la carpeta de otro y encontrar de todo',
      { op: '>>#2 esooo asi conoci bandas q ni sabia' },
      'emule no lo toco mas, me acuerdo de los fakes',
      { de: 4, t: 'bajabas una peli y era cualquier otra cosa' },
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'escribir: la entrevista del otro dia',
    horas: 2,
    mensajes: [
      'en la entrevista el escritor dice que para escribir vas a necesitar mucho tiempo a solas. tengo dos hijos chicos, escribo en el bondi',
      'el bondi cuenta como tiempo a solas',
      'yo escribo a las 6 de la mañana es el unico rato',
      { op: '>>#1 jaja si no hay nadie hablando x telefono' },
      'esta buena la serie de entrevistas, espero la segunda',
    ],
  },
];

// Las más viejas (de 3 a 10 días): alcanzan para que el catálogo, que muestra 60 por página, tenga
// una segunda.
HILOS.push(
  {
    tablon: 'vida-real',
    asunto: 'lei lo de los tintoreros japoneses',
    horas: 75,
    mensajes: [
      'mire toda mi ropa y es negra o gris, me siento en falta',
      'teñi una remera con yerba una vez',
      { op: '>>#1 y??' },
      { de: 1, t: 'quedo color yerba' },
      'jajajajaja',
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'Protect and Survive',
    horas: 78,
    mensajes: [
      'despues de la reseña me baje el manual entero. dice q pongas puertas contra la pared y te metas abajo. mi depto tiene una sola puerta',
      'usa la de la heladera',
      { op: '>>#1 jajaja' },
      'lo mejor son los dibujitos, super tranquilos para lo q estan explicando',
      'yo tengo un paquete de fideos y un bidon de agua, estoy listo',
    ],
  },
  {
    tablon: 'juegos',
    asunto: 'who\'s lila',
    horas: 80,
    mensajes: [
      'no voy a decir nada pero ahora me miro al espejo raro',
      'es el de las caras?',
      { op: 'ese' },
      'lo jugue a las 3 de la mañana error grave',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'ryan gosling sigma male',
    horas: 83,
    mensajes: [
      'desde q lei la nota manejo de noche con campera y sin hablar',
      'literally me',
      'se te ve serio',
      { op: '>>#2 estoy en personaje' },
      'yo mire drive 4 veces seguidas despues de leerla',
      { de: 1, t: 'y no dijiste ni una palabra en todo el finde no?' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'revista El Pendulo',
    horas: 86,
    mensajes: [
      'mi viejo tenia toda la coleccion en el placard y mi vieja la regalo en una mudanza. lo supe hoy',
      'nooooo',
      'ese es el verdadero terror',
      { op: 'le pregunte y me dijo "eran revistas viejas". si mama, ESE era el punto' },
      'buscalas en parque rivadavia',
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'el modelo roblox',
    horas: 88,
    mensajes: [
      'mi sobrino de 9 me explico la economia de un juego de roblox mejor q mi contador. despues lei la nota y todo cerro',
      'jajaja y te pidio robux?',
      { op: '>>#1 obvio, al final de la explicacion' },
      'era todo un pitch',
    ],
  },
  {
    tablon: 'juegos',
    asunto: 'FF7 y la filosofia',
    horas: 91,
    mensajes: [
      'yo a los 12 solo sabia que habia que criar chocobos y ahora me entero q era filosofia',
      'y lo lograste?',
      { op: 'nunca tuve el chocobo dorado' },
      'la nota me hizo llorar un poco no voy a mentir',
      'la escena de la iglesia [spoiler]ya saben cual[/spoiler]',
      { de: 3, t: '>>#4 ni me la nombres' },
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'cronica del mundial en micro',
    horas: 94,
    mensajes: [
      'yo me mareo en el 60 y este tipo cruzo estados unidos en micro',
      'lo del tipo q le ofrecio un sanguche en el micro jaja',
      'quiero la segunda parte',
      { op: '>>#2 creo q sale, esta como primera entrega' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'el gran dios pan y lain',
    horas: 97,
    mensajes: [
      'nunca se me hubiera ocurrido juntar arthur machen con serial experiments lain. ahora veo lain en todos lados',
      'present day present time',
      { op: 'JAJAJA' },
      'la vi a los 15 y no entendi nada, la vi a los 30 y entendi menos',
      'mi router hace un ruido parecido a la intro',
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'aprendi 3 palabras de esperanto',
    horas: 100,
    mensajes: [
      'saluton. dankon. y la otra no me acuerdo',
      'saluton!!',
      { op: '>>#1 saluton!' },
      'ya somos 2 hablantes, falta un pueblo nomas',
      { de: 1, t: 'un idioma sin pueblo, ahora con 2 personas en un foro' },
      'le hable en esperanto a mi gato, me ignoro igual q en castellano',
    ],
  },
  {
    tablon: 'juegos',
    asunto: 'onimusha way of the sword',
    horas: 103,
    mensajes: [
      'tenia el primero en la ps2 y lo que mas me acuerdo es la musica del menu',
      'y absorber almas',
      'yo la memory card con el partido guardado todavia la tengo',
      { op: '>>#2 anda?' },
      { de: 2, t: 'no tengo mas la ps2 jaja' },
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'skate rock argentino',
    horas: 106,
    mensajes: [
      'me entere de bandas q mi primo escuchaba en el walkman y yo no sabia que eran',
      'yo me rompi la muñeca a los 14 en un half pipe de madera',
      { op: '>>#1 como corresponde' },
      'andar y tocar, me gusto el titulo',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'la frecuencia kirlian',
    horas: 109,
    mensajes: [
      'soy de un pueblo de 3 mil personas y es tal cual, a la noche la radio agarra cosas raras',
      'yo escuche un pastor evangelico mezclado con cumbia a las 2 am',
      { op: '>>#1 esa es la frecuencia' },
      'ahora voy a pasar por la ruta 5 con miedo',
    ],
  },
  {
    tablon: 'juegos',
    asunto: 'warhammer the old world',
    horas: 112,
    mensajes: [
      'estoy pintando mi ejercito hace 7 meses, tengo 12 miniaturas pintadas',
      'vas bien',
      'yo tengo la pila de la verguenza en el placard',
      { op: '>>#2 todos tenemos una' },
      'mi pareja me pregunto cuanto gaste y dije "unos pesos"',
      { de: 1, t: 'jajaja unos pesos' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'inquilinos de nuestra memoria digital',
    horas: 115,
    mensajes: [
      'fui a buscar fotos de 2014 y estaban en un servicio que ya no existe. inquilino desalojado',
      'yo tengo todo en un disco externo q hace un ruido raro',
      { op: '>>#1 ese ruido es el reloj' },
      'backup del backup',
      'imprimi las fotos importantes en papel como en 1995 y listo',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'amazing digital circus',
    horas: 118,
    mensajes: [
      'la mira mi hermanita y yo la miraba de reojo, despues de la nota la miro de frente',
      'pomni somos todos',
      'la parte de la salida q no existe',
      { op: '>>#2 como las reuniones del laburo' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'Akira',
    horas: 121,
    mensajes: [
      'la volvi a ver y me quede duro 10 min mirando los creditos',
      'KANEDAAAA',
      'TETSUOOOO',
      { op: 'sabia q iba a pasar esto' },
      'la moto roja es el sueño de todos',
      { de: 4, t: 'yo tengo una zanella' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'blade runner',
    horas: 124,
    mensajes: [
      'la quinta entrega del canon. lei la novela de dick despues y es otra cosa, tiene lo de las ovejas',
      'la oveja electrica es lo mejor del libro',
      'yo lloro con lo de las lagrimas en la lluvia siempre',
      { op: '>>#2 como todos' },
      'ahora le pregunto a mi tostadora si sueña',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'ghost in the shell',
    horas: 127,
    mensajes: [
      'yo la vi en un vhs grabado de la tele con propagandas en el medio',
      'propaganda de shampoo en medio de la escena del mar',
      { op: '>>#1 JAJA posta algo asi' },
      'la musica de kenji kawai es otra cosa',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'Robocop',
    horas: 130,
    mensajes: [
      'no sabia q era una satira, la vi de chico como pelicula de accion',
      'I\'d buy that for a dollar',
      'el ED-209 bajando la escalera jaja',
      { op: '>>#2 lo mejor de la historia del cine' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'pepe',
    horas: 133,
    mensajes: [
      'tenia una carpeta de rare pepes en 2016, nunca la vendi',
      'es tu jubilacion',
      { op: '>>#1 sale mas q mi jubilacion posta' },
      'feels good man',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'crash y mad max',
    horas: 136,
    mensajes: [
      'cada vez q paso por la general paz pienso en ballard ahora',
      'la general paz es fury road sin la musica',
      'witness me',
      { op: '>>#1 con la musica seria mejor' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'alan moore',
    horas: 139,
    mensajes: [
      'el tipo se declaro mago y adora a una serpiente romana. leyenda',
      'glycon',
      { op: '>>#1 ese' },
      'lei watchmen 3 veces y todavia me falta algo',
      'la barba ya es una declaracion',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'la odisea de nolan',
    horas: 142,
    mensajes: [
      'lo del purismo textual esta bien pero yo solo quiero saber si ulises tiene reloj en la peli',
      'jajajaja',
      'si dura 3 horas ya es odisea',
      { op: '>>#2 jaja' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'lovecraft',
    horas: 145,
    mensajes: [
      'yo solo leia lovecraft para asustarme y ahora hay lecturas politicas y todo',
      'ph\'nglui mglw\'nafh...',
      { op: '>>#1 no sigas' },
      'mi gato se llama cthulhu y hace honor',
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'proteinas y deep learning',
    horas: 148,
    mensajes: [
      '200 millones de estructuras de proteinas y yo no puedo ordenar mis tuppers',
      'jajaja los tuppers sin tapa',
      'lo lei 2 veces y creo q entendi el 40%',
      { op: '>>#2 es un buen porcentaje' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'la nota de claude code',
    horas: 151,
    mensajes: [
      'le mostre la nota de claude code a mi jefe y me pidio q haga el doble',
      'error de principiante',
      'nunca mostrar nada al jefe',
      { op: 'aprendi la leccion' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'sueñan los modelos de lenguaje',
    horas: 154,
    mensajes: [
      'las dos charlas con chatgpt sobre filosofia de la mente. la parte 1 es de cuando el 3 contestaba cualquier cosa',
      'medio nostalgico ya',
      { op: '>>#1 nostalgia de hace 3 años jaja' },
      'el titulo es de lo mejor de la pagina',
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'IA y poesia',
    horas: 157,
    mensajes: [
      'me dio ganas de escribir un poema. escribi uno. es malo pero es mio',
      'subilo',
      { op: 'ni loco' },
      'el poema malo propio > el poema promedio',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'nick land',
    horas: 160,
    mensajes: [
      'lei el articulo definitivo sobre nick land. entendi como la mitad, la otra mitad me dio dolor de cabeza',
      'es normal',
      'los neologismos son un juego aparte',
      { op: '>>#1 menos mal' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'sloterdijk: volverse ingobernable',
    horas: 163,
    mensajes: [
      'despues de la nota de sloterdijk decidi volverme ingobernable. hoy no hice la cama',
      'arrancamos por algo',
      'mañana no lavas los platos y es la revolucion',
      { op: '>>#2 no tampoco la pavada' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'el quinto eon',
    horas: 166,
    mensajes: [
      'la nota sobre liber null y la magia del caos. no entendi si es para hacer o para leer',
      'para leer y despues ver q pasa',
      'mi tia hace magia del caos con las velas y no leyo nada',
      { op: '>>#2 tu tia es la verdadera' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'glosario de filosofia de la tecnica',
    horas: 169,
    mensajes: [
      'lo tengo abierto en una pestaña hace 2 semanas, cuenta como leido?',
      'si',
      'yo tengo 80 pestañas asi',
      { op: '>>#2 somos una comunidad' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'ingenieria inversa a la mierdificacion',
    horas: 172,
    mensajes: [
      'mi impresora me pide suscripcion para imprimir en color. lo tomo como algo personal',
      'la impresora es el enemigo desde siempre',
      { op: '>>#1 office space tenia razon' },
      'la mia no imprime si no le pongo el cartucho original, ni en blanco y negro',
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'guia cyberciruja',
    horas: 175,
    mensajes: [
      'fui a revisar los permisos del celu despues de la guia. la linterna tenia acceso a los contactos',
      'la linterna jajajaja',
      'para q quiere la linterna tus contactos',
      { op: '>>#2 para iluminarlos supongo' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'anonimato en internet',
    horas: 178,
    mensajes: [
      'la nota en defensa del anonimato. la lei en un foro anonimo, me parecio correcto',
      'muy meta',
      { op: 'hola desde el anonimato' },
      'hola',
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'low tech high life',
    horas: 181,
    mensajes: [
      'despues de leer lo de low tech me compre una radio a pilas. escucho am y me siento un abuelo feliz',
      'am a la tarde con mate es lo mas',
      'yo volvi al reloj de pulsera, sin smartwatch',
      { op: '>>#2 y como sabes cuantos pasos diste' },
      { de: 2, t: 'no se y soy feliz' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'proteger el cerebro del algoritmo',
    horas: 184,
    mensajes: [
      'la nota dice q de 11 millones de bits procesamos 50. los mios se los lleva el tiktok de recetas',
      'recetas q nunca haces',
      { op: '>>#1 nunca, ni una' },
      'yo borre la app y la volvi a bajar a las 2 horas',
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'lo argentino antes de la argentina',
    horas: 187,
    mensajes: [
      'el asado ya existia antes q el pais, eso explica todo',
      'el asado es anterior al estado',
      'la rosca tambien',
      { op: '>>#2 JAJAJA' },
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'ricardo fort el super chad',
    horas: 190,
    mensajes: [
      'no sabia nada de su juventud, la primera entrega es buenisima',
      'maiameee',
      'quiero la segunda parte ya',
      { op: '>>#1 no podia faltar' },
      'los chocolates felfort eran muy ricos igual',
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'posadas encarnacion',
    horas: 193,
    mensajes: [
      'la cronica de la frontera. soy de posadas y la lei 3 veces, esta muy bien contado',
      'cruzabas a comprar a encarnacion?',
      { op: '>>#1 todos, toda la vida' },
      'yo fui una vez y me volvi con 4 ventiladores',
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'la guia de fanzines x2',
    horas: 196,
    mensajes: [
      'no se si ya hubo un post de esto pero hice un fanzine sobre mi perro',
      'cuantas paginas',
      { op: '8, como dice la nota' },
      'la tirada?',
      { op: '>>#3 1. para mi mama' },
    ],
  },
  {
    tablon: 'juegos',
    asunto: 'el random podcast',
    horas: 199,
    mensajes: [
      'alguien escucha el random podcast de 421? lo pongo para dormir y no lo digo como algo malo',
      'jaja yo tmb',
      'lo escucho lavando los platos',
      { op: '>>#2 el podcast de los platos' },
    ],
  },
  {
    tablon: 'tecnologia',
    asunto: 'looksmaxxing',
    horas: 202,
    mensajes: [
      'aprendi que es el mewing y ahora apreto la lengua contra el paladar todo el dia sin querer',
      'jajaja yo tmb ahora',
      'gracias por esto',
      { op: 'de nada, ya no hay vuelta atras' },
    ],
  },
  {
    tablon: 'cultura',
    asunto: 'la revista de 421',
    horas: 205,
    mensajes: [
      'me llego la revista. la deje en la mesa del living y mi viejo la agarro primero',
      'y?',
      { op: 'la esta leyendo hace 2 dias, no me la devuelve' },
      'perdiste',
    ],
  },
  {
    tablon: 'vida-real',
    asunto: 'alfabetizacion material',
    horas: 208,
    mensajes: [
      'me dio culpa cambiar el celular, lo voy a hacer durar 5 años',
      'cuantos tiene',
      { op: '>>#1 1 y medio' },
      'jajaja faltan 3 y medio',
      'yo tengo uno de 2018 con la pantalla rajada y sigue',
    ],
  },
);
